### ISSUE TITLE
ExportCSV - test class fails

### ISSUE THREAD

**Issue by solo-1234** [captechconsulting/lightning-flow-utils#1]
Hi,

Thanks for a great utility!

I'm running into an issue where I get a test failure on line 47:
Assertion Failed: Expected: Test1,,, Actual: Test1,,Test1

I tried commenting out that line but then I get another error on line 49:
Assertion Failed: Expected: Test3,abc@gmail.com,, Actual: Test3,abc@gmail.com,Jonny Test3

Any idea why this would be?

Thanks!

@sillyrags

**Comment by sillyrags** [comment]
Thanks for filing the issue @solo-1234. We're looking into now and I'll keep you posted.

**Comment by sillyrags** [comment]
@solo-1234 - Just to clarify, you are only having trouble with the test class passing? Your use case for the action outputs the expected results?

**Comment by solo-1234** [comment]
Thanks for responding! You are correct, the flow action works perfectly, just the test class fails.

**Comment by solo-1234** [comment]
I ended up commenting out lines 47, 49, and 56. The rest of the tests pass so this works :)

Thanks for your help!
